

## SERVIDOR
server:
  port: 8083
  compression:
    enabled: true
  error:
    include-stacktrace: never
  servlet:
    context-path: /

## APLICACION
spring:
  main:
     allow-bean-definition-overriding: true
  application:
    name: online-store     
    version: v1.0.0
    restPort: ${server.port}
  messages:
    encoding: UTF-8  

#Database
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017      
      authentication-database: admin
      database: test      
      repositories:
        type: reactive


## APPLICATION
application:
  log: /logs/
  ##secret and salt for encrypt or decrypt information. 
  secret: 763Inkjjht3rg4t10h$
  salt: Db3.*3Y^8"x'\Hkd
  services:
    ping: /ping
    # API's
    user-login: /api/v1/user-login/
  ivaValue: 0.19
  deletePurchanseTax: 0.1
  maxDeleteTime: 12
  maxUpdateTime: 5
  minimumPurchanse: 70000



    
## LOGGGER
logging:
  level:
    root: INFO
    org.springframework: INFO
    co.com.aruma: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss:SSS} [%5p] [%t] - %15c{1}:[%4L] - %m%n"
